version: "2"
services:
    php:
        build:
          context: .docker/
          dockerfile: Dockerfile
        volumes:
          - ./:/var/www/html/
          - .docker/php/apache2/apache2.conf:/etc/apache2/apache2.conf
        ports:
          - "8080:80"